var searchData=
[
  ['dataaccess_150',['DataAccess',['../namespace_infrastructure_1_1_data_access.html',1,'Infrastructure']]],
  ['efcoredataaccess_151',['EfCoreDataAccess',['../namespace_infrastructure_1_1_data_access_1_1_ef_core_data_access.html',1,'Infrastructure::DataAccess']]],
  ['iansweroptionrepository_152',['IAnswerOptionRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_answer_option_repository.html',1,'Core::Domain::Repositories']]],
  ['icoreunitofwork_153',['ICoreUnitOfWork',['../interface_core_1_1_domain_1_1_repositories_1_1_i_core_unit_of_work.html',1,'Core::Domain::Repositories']]],
  ['id_154',['Id',['../class_core_1_1_domain_1_1_entites_1_1_examiner.html#aae3e339037858c644e74dd03c2b88ecc',1,'Core.Domain.Entites.Examiner.Id()'],['../class_core_1_1_domain_1_1_entites_1_1_group.html#a32e265997f7e5de133a15a1ff3b4813b',1,'Core.Domain.Entites.Group.Id()'],['../class_core_1_1_domain_1_1_entites_1_1_question.html#af5bcc0b73b9e4c12126f1dcc2d349834',1,'Core.Domain.Entites.Question.Id()'],['../class_core_1_1_domain_1_1_entites_1_1_student.html#a6737f2f3222194500e80ce9cdfbfe575',1,'Core.Domain.Entites.Student.Id()'],['../class_core_1_1_domain_1_1_entites_1_1_student_test_question.html#a29187258ee13da6a2350415a46aa3300',1,'Core.Domain.Entites.StudentTestQuestion.Id()'],['../class_core_1_1_domain_1_1_entites_1_1_student_test_question_response.html#af04e43d4c44daaacf03b61e27d4d6cbf',1,'Core.Domain.Entites.StudentTestQuestionResponse.Id()'],['../class_core_1_1_domain_1_1_entites_1_1_test.html#a8fb1b7f0aed08bd8851859bd4060ac6a',1,'Core.Domain.Entites.Test.Id()'],['../class_core_1_1_domain_1_1_entites_1_1_test_statistic.html#a89998b8c65ec6b16567d81169ba12664',1,'Core.Domain.Entites.TestStatistic.Id()']]],
  ['iexaminerrepository_155',['IExaminerRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_examiner_repository.html',1,'Core::Domain::Repositories']]],
  ['igrouprepository_156',['IGroupRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_group_repository.html',1,'Core::Domain::Repositories']]],
  ['ijobservice_157',['IJobService',['../interface_core_1_1_domain_1_1_services_1_1_external_1_1_job_service_1_1_i_job_service.html',1,'Core::Domain::Services::External::JobService']]],
  ['imailservice_158',['IMailService',['../interface_core_1_1_domain_1_1_services_1_1_external_1_1_mail_service_1_1_i_mail_service.html',1,'Core::Domain::Services::External::MailService']]],
  ['infrastructure_159',['Infrastructure',['../namespace_infrastructure.html',1,'']]],
  ['initial_160',['Initial',['../class_auth_1_1_infrastructure_1_1_data_access_1_1_ef_core_data_access_1_1_migrations_1_1_initial.html',1,'Auth::Infrastructure::DataAccess::EfCoreDataAccess::Migrations']]],
  ['initial_5fcreate_161',['Initial_Create',['../class_core_1_1_infrastructure_1_1_data_access_1_1_ef_core_data_access_1_1_migrations_1_1_initial___create.html',1,'Core::Infrastructure::DataAccess::EfCoreDataAccess::Migrations']]],
  ['integrationsetup_162',['IntegrationSetUp',['../class_tests_1_1_core_application_services_tests_1_1_integration_set_up.html',1,'Tests::CoreApplicationServicesTests']]],
  ['iquestionrepository_163',['IQuestionRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_question_repository.html',1,'Core::Domain::Repositories']]],
  ['irepository_164',['IRepository',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20answeroption_20_3e_165',['IRepository&lt; AnswerOption &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20examiner_20_3e_166',['IRepository&lt; Examiner &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20group_20_3e_167',['IRepository&lt; Group &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20question_20_3e_168',['IRepository&lt; Question &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20student_20_3e_169',['IRepository&lt; Student &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20studenttest_20_3e_170',['IRepository&lt; StudentTest &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20studenttestquestion_20_3e_171',['IRepository&lt; StudentTestQuestion &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20test_20_3e_172',['IRepository&lt; Test &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20teststatistic_20_3e_173',['IRepository&lt; TestStatistic &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['isactive_174',['IsActive',['../class_core_1_1_domain_1_1_entites_1_1_test.html#a7fbcb848f3cf315f755c03c8c97879d6',1,'Core::Domain::Entites::Test']]],
  ['istestpassed_175',['IsTestPassed',['../class_core_1_1_domain_1_1_entites_1_1_student_test.html#a09b4038eed9ce19822abd3cec3f7ebc0',1,'Core::Domain::Entites::StudentTest']]],
  ['istudentrepository_176',['IStudentRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_student_repository.html',1,'Core::Domain::Repositories']]],
  ['istudenttestquestionrepository_177',['IStudentTestQuestionRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_student_test_question_repository.html',1,'Core::Domain::Repositories']]],
  ['istudenttestrepository_178',['IStudentTestRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_student_test_repository.html',1,'Core::Domain::Repositories']]],
  ['itestrepository_179',['ITestRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_test_repository.html',1,'Core::Domain::Repositories']]],
  ['iteststatisticrepository_180',['ITestStatisticRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_test_statistic_repository.html',1,'Core::Domain::Repositories']]],
  ['iunitofwork_181',['IUnitOfWork',['../interface_common_1_1_utils_1_1_i_unit_of_work.html',1,'Common::Utils']]],
  ['seeds_182',['Seeds',['../namespace_infrastructure_1_1_data_access_1_1_ef_core_data_access_1_1_seeds.html',1,'Infrastructure::DataAccess::EfCoreDataAccess']]]
];
