var searchData=
[
  ['iansweroptionrepository_371',['IAnswerOptionRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_answer_option_repository.html',1,'Core::Domain::Repositories']]],
  ['icoreunitofwork_372',['ICoreUnitOfWork',['../interface_core_1_1_domain_1_1_repositories_1_1_i_core_unit_of_work.html',1,'Core::Domain::Repositories']]],
  ['iexaminerrepository_373',['IExaminerRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_examiner_repository.html',1,'Core::Domain::Repositories']]],
  ['igrouprepository_374',['IGroupRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_group_repository.html',1,'Core::Domain::Repositories']]],
  ['ijobservice_375',['IJobService',['../interface_core_1_1_domain_1_1_services_1_1_external_1_1_job_service_1_1_i_job_service.html',1,'Core::Domain::Services::External::JobService']]],
  ['imailservice_376',['IMailService',['../interface_core_1_1_domain_1_1_services_1_1_external_1_1_mail_service_1_1_i_mail_service.html',1,'Core::Domain::Services::External::MailService']]],
  ['initial_377',['Initial',['../class_auth_1_1_infrastructure_1_1_data_access_1_1_ef_core_data_access_1_1_migrations_1_1_initial.html',1,'Auth::Infrastructure::DataAccess::EfCoreDataAccess::Migrations']]],
  ['initial_5fcreate_378',['Initial_Create',['../class_core_1_1_infrastructure_1_1_data_access_1_1_ef_core_data_access_1_1_migrations_1_1_initial___create.html',1,'Core::Infrastructure::DataAccess::EfCoreDataAccess::Migrations']]],
  ['integrationsetup_379',['IntegrationSetUp',['../class_tests_1_1_core_application_services_tests_1_1_integration_set_up.html',1,'Tests::CoreApplicationServicesTests']]],
  ['iquestionrepository_380',['IQuestionRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_question_repository.html',1,'Core::Domain::Repositories']]],
  ['irepository_381',['IRepository',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20answeroption_20_3e_382',['IRepository&lt; AnswerOption &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20examiner_20_3e_383',['IRepository&lt; Examiner &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20group_20_3e_384',['IRepository&lt; Group &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20question_20_3e_385',['IRepository&lt; Question &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20student_20_3e_386',['IRepository&lt; Student &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20studenttest_20_3e_387',['IRepository&lt; StudentTest &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20studenttestquestion_20_3e_388',['IRepository&lt; StudentTestQuestion &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20test_20_3e_389',['IRepository&lt; Test &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['irepository_3c_20teststatistic_20_3e_390',['IRepository&lt; TestStatistic &gt;',['../interface_common_1_1_utils_1_1_i_repository.html',1,'Common::Utils']]],
  ['istudentrepository_391',['IStudentRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_student_repository.html',1,'Core::Domain::Repositories']]],
  ['istudenttestquestionrepository_392',['IStudentTestQuestionRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_student_test_question_repository.html',1,'Core::Domain::Repositories']]],
  ['istudenttestrepository_393',['IStudentTestRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_student_test_repository.html',1,'Core::Domain::Repositories']]],
  ['itestrepository_394',['ITestRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_test_repository.html',1,'Core::Domain::Repositories']]],
  ['iteststatisticrepository_395',['ITestStatisticRepository',['../interface_core_1_1_domain_1_1_repositories_1_1_i_test_statistic_repository.html',1,'Core::Domain::Repositories']]],
  ['iunitofwork_396',['IUnitOfWork',['../interface_common_1_1_utils_1_1_i_unit_of_work.html',1,'Common::Utils']]]
];
